spring:
  mvc:
    locale: ru_RU
  http:
    encoding:
      charset: UTF-8
      force: true
  liquibase.change-log: classpath:liquibase/db.changelog-master.xml

logging:
  level:
    ROOT: INFO
    org.springframework: WARN
    ua.epam: INFO

---
spring:
  profiles: h2local
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: sa
  h2:
    console:
      enabled: true
      path: /h2-console