spring:
  profiles:
    active: h2local
  mvc:
    locale: ru_RU
    locale-resolver: fixed
  http:
    encoding:
      charset: UTF-8
      force: true
  liquibase.change-log: classpath:liquibase/db.changelog-master.xml

logging:
  level:
    ROOT: INFO
    org.springframework: WARN

---
spring:
  profiles: h2local
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
  h2:
    console:
      enabled: true
      path: /h2-console